services:
  svelte:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - filemanager-net

  api:
    build: ./backend
    ports:
      - "1402:1402"
      - "1414:1414"
    volumes:
      - /yuru/remishare-files:/app/files
    networks:
      - filemanager-net

networks:
  filemanager-net:
    driver: bridge